### ISSUE TITLE
 Error in executing ansible script

### ISSUE THREAD

**Issue by Laxman-SM** [adenot/blog-ansible-provision-ec2#1]
unable to get reason for failing any suggestion to work this playbook. tested on both Macbook and vagrant vm. on both environment getting same error.

ec2_keypair: "pgstaging"
ec2_security_group: "zoo"
ec2_instance_type: "m3.medium"
ec2_image: "ami-561d8241"
ec2_subnet_ids: ['vpc-57b0423','subnet-4feead6']
ec2_region: "us-east-1"
ec2_tag_Name: "ansible-kafka"
ec2_tag_Type: "ansible-kafka"
ec2_tag_Environment: "vpc-stage"
ec2_volume_size: 8

ansible-playbook -vv -i inventory  -e "type=ansible-kafka" provision-ec2.yml

PLAY [localhost] *************************************************************\* 

TASK: [include_vars ec2_vars/{{type}}.yml] ***********************************\* 
failed: [127.0.0.1] => {"failed": true, "file": "/Users/laxmansingh/images-Docker/hadoop-multi-server-ansible/laxman/ec2_vars/ansible-kafka.yml"}
msg: Source file not found.

FATAL: all hosts have already failed -- aborting

**Comment by adenot** [comment]
@Laxman-SM Did you create the file ansible-kafka.yml inside ec2_vars? The playbook will look for the file in that location by default.

**Comment by adenot** [comment]
Closing issue. Feel free to reopen if problem still persists.
